package com.mehery.pushapp

object PushAppErrorCodes {
    const val NOT_INITIALIZED = "NOT_INITIALIZED"
    const val INVALID_APP_ID = "INVALID_APP_ID"
    const val APP_ID_REQUIRED = "APP_ID_REQUIRED"
    const val CONTEXT_UNAVAILABLE = "CONTEXT_UNAVAILABLE"
    const val REGISTER_REQUIRED = "REGISTER_REQUIRED"
    const val EMPTY_TOKEN = "EMPTY_TOKEN"
    const val REGISTER_FAILED = "REGISTER_FAILED"
    const val EMPTY_USER_ID = "EMPTY_USER_ID"
    const val LOGIN_FAILED = "LOGIN_FAILED"
    const val LOGOUT_FAILED = "LOGOUT_FAILED"
    const val CUSTOMER_PROFILE_FAILED = "CUSTOMER_PROFILE_FAILED"
    const val MISSING_CODE = "MISSING_CODE"
    const val MISSING_PROFILE_DATA = "MISSING_PROFILE_DATA"
    const val INVALID_PROFILE_DATA = "INVALID_PROFILE_DATA"
    const val MISSING_EVENT_NAME = "MISSING_EVENT_NAME"
    const val MISSING_EVENT_DATA = "MISSING_EVENT_DATA"
    const val INVALID_EVENT_DATA = "INVALID_EVENT_DATA"
    const val MISSING_PAGE_NAME = "MISSING_PAGE_NAME"
    const val MISSING_PLACEHOLDER_ID = "MISSING_PLACEHOLDER_ID"
    const val MISSING_UI_BOUNDS = "MISSING_UI_BOUNDS"
    const val MISSING_TARGET_ID = "MISSING_TARGET_ID"
    const val ACTIVITY_UNAVAILABLE = "ACTIVITY_UNAVAILABLE"
    const val PLACEHOLDER_FAILED = "PLACEHOLDER_FAILED"
    const val TOOLTIP_FAILED = "TOOLTIP_FAILED"
    const val MISSING_NOTIFICATION_TOKEN = "MISSING_NOTIFICATION_TOKEN"
    const val MISSING_NOTIFICATION_EVENT = "MISSING_NOTIFICATION_EVENT"

    @JvmStatic
    fun message(code: String): String = when (code) {
        NOT_INITIALIZED -> "Call PushApp.initialize() before this method."
        INVALID_APP_ID ->
            "Initialize failed. appId must include a tenant prefix before the first '_' (e.g. demo_1763369170735)."
        APP_ID_REQUIRED -> "appId is required (channel id / App ID)."
        CONTEXT_UNAVAILABLE -> "Android context is not available."
        REGISTER_REQUIRED -> "Call PushApp.register() before login()."
        EMPTY_TOKEN -> "Push token is required. Wait for FCM/APNs token or pass it from JS."
        REGISTER_FAILED -> "Device registration failed. Check the push token and network connection."
        EMPTY_USER_ID -> "userId is required."
        LOGIN_FAILED -> "Login failed. The server did not confirm the device link."
        LOGOUT_FAILED -> "Logout failed. Local session was cleared but the server delink call failed."
        CUSTOMER_PROFILE_FAILED -> "Customer profile update failed."
        MISSING_CODE -> "code is required (e.g. userId_deviceId)."
        MISSING_PROFILE_DATA -> "additionalInfo and cohorts are required and must be objects."
        INVALID_PROFILE_DATA -> "Failed to parse additionalInfo or cohorts."
        MISSING_EVENT_NAME -> "eventName is required."
        MISSING_EVENT_DATA -> "eventData is required and must be an object."
        INVALID_EVENT_DATA -> "Failed to parse eventData."
        MISSING_PAGE_NAME -> "pageName is required."
        MISSING_PLACEHOLDER_ID -> "placeholderId is required."
        MISSING_UI_BOUNDS -> "x, y, width, and height are required."
        MISSING_TARGET_ID -> "targetId is required."
        ACTIVITY_UNAVAILABLE -> "Activity is not available."
        PLACEHOLDER_FAILED -> "Placeholder operation failed."
        TOOLTIP_FAILED -> "Tooltip target operation failed."
        MISSING_NOTIFICATION_TOKEN -> "token is required."
        MISSING_NOTIFICATION_EVENT -> "event is required."
        else -> "PushApp operation failed."
    }
}
